<?php $prdList = $this->getProductToShow(); ?>
<?php 
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
$type = 'widget-product-grid';
$image = 'category_page_grid';
$imageTwo = 'category_page_two_list';
$quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');
?>
<?php if($this->getData('per_row') != null){
	$perRow = $this->getData('per_row');
}else {
	$perRow = $themeSettings['catalog']['per_row'];
} ?>
<div class="block-deals <?php if($this->getData('custom_class')): ?><?php echo $this->getData('custom_class')?><?php endif;?>">
<?php if($this->getTitle() != ""): ?>
	<div class="block-title">
		<h4><?php echo $this->getTitle(); ?></h4>
	</div>
<?php endif ?>
<?php if(count($prdList) > 0): ?>
	<div id="deal_products" class="products-grid deal-grid deal-carousel">
		<?php foreach($prdList as $product_id): ?>
			<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
			<?php $productModel = $objectManager->create('Magento\Catalog\Model\Product'); ?>
			<?php $_product = $productModel->load($product_id); ?>
			<?php $_itemNameStripped = $block->stripTags($_product->getName(), null, true); ?>
			<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
			<?php $size = $themeHelper->getImageSize(); ?>
			<?php $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();  ?>
			<?php if($this->getSlider() == 1): ?>
				<div class="product-item item">
			<?php else: ?>
				<div class="item <?php echo $themeHelper->getColClass($perRow) ?> <?php echo $themeHelper->getClearClass($perRow, $i) ?>">
			<?php endif ?>
				<div class="product-item-info product-content">
					<div class="product-top">
						<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_product) ?>" class="product-item-photo">
							<img src="<?php echo $productImage; ?>" alt="<?php echo $_itemNameStripped ?>" class="img-responsive product-image-photo"/>							
						</a>
						<div class="button-quickview">
							<?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
						</div>
						<?php echo $themeHelper->getProductLabel($_product) ?>
						<?php echo $this->getLayout()->createBlock('MGS\Mpanel\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Mpanel::products/deals/item.phtml')->toHtml(); ?>						
					</div>
					<div class="product-desc product-item-details">
						<div class="cate-name text-center"><?php echo $themeHelper->getCategoryName($_product,$this->getData('title'),'') ?></div>
						<h4 class="product-item-name product-name">
							<a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_product) ?>" title="<?php echo $_itemNameStripped ?>"><?php echo $_product->getName() ?></a>
						</h4>
						<div class="rating-price">
							<?php  echo $block->getProductPrice($_product) ?>
							<?php echo $block->getReviewsSummaryHtml($_product, 'short', true)?>
						</div>
						<div class="controls">
							<div class="add-to-cart">
								<?php if ($_product->isSaleable()): ?>
								<?php $url = $this->getAddToCartUrl($_product) ?>
									<form data-role="tocart-form" action="<?php echo $url; ?>" method="post">
										<input type="hidden" name="product" value="<?php echo $_product->getId(); ?>">
										<input type="hidden" name="uenc" value="<?php echo $this->getEncodedUrl($url) ?>">
										<?php echo $block->getBlockHtml('formkey')?>
										<button class="tocart btn-icon btn btn-default" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
											<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
										</button>
									</form>
								<?php else: ?>
									<?php if ($_product->getIsSalable()): ?>
										<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
									<?php else: ?>
										<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
									<?php endif; ?>
								<?php endif; ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		<?php endforeach ?>
	</div>
	<?php if($this->getSlider() == 1): ?>
		<script type="text/javascript">
			require([
				'jquery',
				'mgs/owlcarousel'
			], function ($) {
				var owl = $('#deal_products');
				owl.owlCarousel({
					items: <?php echo $perRow ?>,
					autoPlay: false,
					stopOnHover: false,
					margin: 30,
					nav: <?php if($this->getSliderControl() == 1): ?>true<?php else: ?>false<?php endif ?>,
					navText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
					dots: <?php if($this->getSliderDots() == 1): ?>true<?php else: ?>false<?php endif;?>,
					responsive:{ 0 : {items: 1}, 520 : {items: 2}, 768 : {items: 2}, 992 : {items: 1}, 1200 : {items: <?php echo $perRow ?>} }
				});
			});    
		</script>
	<?php endif ?>
<?php else: ?>
	<div class="alert alert-danger">
		<?php echo __('No deal product to show'); ?>
	</div>
<?php endif ?>
</div>