<?php
/*
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GNU General Public License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/gpl-license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@refersion.com so we can send you a copy immediately.
 *
 * @category   TCS
 * @package    Tcs_Codshippingbooking
 * @copyright  Copyright (c) 2015 TCS (Pvt) Ltd.
 * @author	   TCS Developer <kamran.haider@tcs-e.com>
 * @license    http://opensource.org/licenses/gpl-license GNU General Public License
 */
?>
<?php $data = $this->getFormData(); ?>
<div style="" id="">
  <div class="entry-edit">
    <div class="entry-edit-head">
      <h4 class="icon-head head-edit-form fieldset-legend">Booking Information</h4>
      <div class="form-buttons"></div>
    </div>
    <div id="_accountbase_fieldset" class="fieldset ">
      <div class="hor-scroll">
      	<form name="cod_shipping_booking" id="codShippingBooking" action="<?php echo $this->getFormAction()?>">
        <input type="hidden" name="booking[order_id]" id="orderId" value="<?php echo $data['order_id']?>" />
        <table cellspacing="0" class="form-list">
          <tbody>
          	<tr>
              <td class="label"><label for="">Cost Center</label></td>
              <td class="value"><?php echo $data['costCenter']?><input type="hidden" name="booking[costCenterCode]" id="costCenterCode" value="<?php echo $data['costCenterCode']?>" /></td>
            </tr>
            <tr>
              <td class="label"><label for="">Consignee Name<span class="required">*</span></label></td>
              <td class="value">
                  <input type="text"  class="required-entry input-text" value="<?php echo $data['consigneeName']?>" name="booking[consigneeName]" id="consigneeName">
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Consignee Address<span class="required">*</span></label></td>
              <td class="value">
              		<textarea name="booking[consigneeAddress]" id="consigneeAddress" class="required-entry textarea"><?php echo $data['consigneeAddress']?></textarea>
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Consignee Mobile No.<span class="required">*</span></label></td>
              <td class="value">
                  <input type="text"  class="required-entry input-text validate-mobileno" value="<?php echo $data['consigneeMobNo']?>" name="booking[consigneeMobNo]" id="consigneeMobNo">
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Consignee Email</label></td>
              <td class="value">
                  <input type="text"  class=" input-text validate-email" value="<?php echo $data['consigneeEmail']?>" name="booking[consigneeEmail]" id="consigneeEmail">
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Origin City Name</label></td>
              <td class="value">
                  <select name="booking[originCityName]" id="originCityName" class="select"><?php echo $data['originCityOptions']?></select>
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Destination City Name<span class="required">*</span></label></td>
              <td class="value">
              		<select name="booking[destinationCityName]" id="destinationCityName" class="required-entry select"><?php echo $data['destinationCityOptions']?></select><br /><?php echo $data['select_message'] ?>
                  
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Pieces</label></td>
              <td class="value">
                  <input type="text"  class=" input-text validate-greater-than-zero validate-decimal" value="<?php echo $data['pieces']?>" name="booking[pieces]" id="pieces">
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Weight(in kg.)<span class="required">*</span></label></td>
              <td class="value">
                  <input type="text"  class="required-entry input-text validate-greater-than-zero validate-decimal" value="<?php echo $data['weight']?>" name="booking[weight]" id="weight">
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">COD Amount<span class="required">*</span></label></td>
              <td class="value">
                  <input type="text"  class="required-entry input-text validate-greater-than-zero validate-decimal" value="<?php echo $data['codAmount']?>" name="booking[codAmount]" id="codAmount">
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Customer Reference No.</label></td>
              <td class="value">
                  <input type="text"  class=" input-text validate-digits" value="<?php echo $data['custRefNo']?>" name="booking[custRefNo]" id="custRefNo">
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Product Details</label></td>
              <td class="value">
                  <textarea name="booking[productDetails]" id="productDetails"><?php echo $data['productDetails']?></textarea>
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Fragile<span class="required">*</span></label></td>
              <td class="value">
                  <select class="required-entry select" name="booking[fragile]" id="fragile">
                  <option value="yes">Yes</option>
                  <option selected="selected" value="no">No</option>
                	</select>
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Service<span class="required">*</span></label></td>
              <td class="value">
                  <select class="required-entry select" name="booking[services]" id="services">
                  <option selected="1" value="O">Overnight</option>
                  <option value="D">2nd Day</option>
                  <option value="S">Same day</option>
                  <option value="OLE">Overland</option>
                	</select>
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Remarks</label></td>
              <td class="value">
                  <textarea name="booking[remarks]" id="remarks"><?php echo $data['remarks']?></textarea>
              </td>
            </tr>
            <tr>
              <td class="label"><label for="">Insurance Value</label></td>
              <td class="value">
                  <input type="text"  class=" input-text validate-number validate-zero-or-greater" value="<?php echo $data['insuranceValue']?>" name="booking[insuranceValue]" id="insuranceValue">
              </td>
            </tr>
            <tr>
            	<td></td>
              <td>
              	<button style="" onclick="javascript:return submitForm();" class="scalable save" type="button" title="Save Customer" ><span>Post</span></button>
              </td>
            </tr>
            <tr> </tr>
          </tbody>
        </table>
        </form>
<script type="text/javascript">
//< ![CDATA[

function submitForm(){
	if(Validation) {
		Validation.addAllThese([
			['validate-mobileno','Enter correct mobile number (Eg:919986858483)',
			function(v){
			var timePat =/^[+]*[(]{0,1}[0-9]{1,3}[)]{0,1}[-\s\./0-9]*$/g;
			if(!timePat.test(v)){
				return false;
			}
			else{
				return true;
			}
		}
		],
		['validate-decimal','Numbers with/without decimals are allowed.',
			function(v){
			var timePat =/^\d+(\.\d+)?$/;
			if(!timePat.test(v)){
				return false;
			}
			else{
				return true;
			}
		}
		]
		])
	};
	var customForm = new varienForm('codShippingBooking');
	var validator = new Validation('codShippingBooking', {immediate : true});
	var vali = validator.validate();
	if(vali){
		codShippingBooking.submit();
	}
	else{
		return false;	
	}
}
//]]>
</script>
      </div>
    </div>
  </div>
</div>
